/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#490080',
        'surface-container-low': '#1a1a2a',
        'on-error-container': '#ffdad6',
        'outline-variant': '#3c4a42',
        'on-background': '#e3e0f7',
        tertiary: '#ddb7ff',
        outline: '#86948a',
        background: '#121221',
        'tertiary-container': '#c487ff',
        primary: '#4edea3',
        'secondary-container': '#0566d9',
        'on-error': '#690005',
        'on-secondary': '#002e6a',
        secondary: '#adc6ff',
        'primary-container': '#10b981',
        'surface-container-highest': '#333344',
        'surface-bright': '#383849',
        'on-surface': '#e3e0f7',
        'surface-container': '#1e1e2e',
        surface: '#121221',
        'surface-variant': '#333344',
        'on-primary-container': '#00422b',
        'on-surface-variant': '#bbcabf',
        'surface-container-lowest': '#0d0d1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base_unit: '8px',
        gutter: '24px',
        stack_sm: '12px',
        stack_md: '20px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '20px' }],
      },
    },
  },
  plugins: [],
};
